trainer:
  target: trainer.TrainerFusion


autoencoder:

model:
  target: models.unet.UNetModelSwin
  ckpt_path: ~
  params:
    image_size: 192
    in_channels: 2
    model_channels: 160
    out_channels: 1
    attention_resolutions: [48, 24, 12, 6]
    dropout: 0
    channel_mult: [1, 1, 2, 2, 4, 4]
    num_res_blocks: [2, 2, 2, 2, 2, 2]
    conv_resample: True
    dims: 2
    use_fp16: False
    num_head_channels: 32
    use_scale_shift_norm: True
    resblock_updown: False
    swin_depth: 2
    swin_embed_dim: 256
    window_size: 6
    mlp_ratio: 4
    cond_lq: True
    lq_size: 192

diffusion:
  target: models.script_util.create_gaussian_diffusion
  params:
    schedule_name: exponential
    schedule_kwargs:
      power: 0.3
    etas_end: 0.99
    steps: 4
    min_noise_level: 0.2
    kappa: 2.0
    weighted_mse: False
    predict_type: xstart
    timestep_respacing: ~
    scale_factor: 1.0
    normalize_input: True
    latent_flag: True

data:
  train:
    type: demo
    params:
      dataset_path: 'MyDatasets/Demo'
      isTrain: True
  val:
    type: demo
    params:
      dataset_path: 'MyDatasets/Demo'
      isTrain: False

train:
  # learning rate
  lr: 5e-5                      # learning rate
  lr_min: 2e-5                  # learning rate
  lr_schedule: cosin
  warmup_iterations: 5000
  F1_step: -1
  # dataloader
  batch: [4, 4]
  microbatch: 4
  num_workers: 16
  prefetch_factor: 2
  # optimization settings
  weight_decay: 0
  ema_rate: 0.999
  iterations: 100000            # total iterations
  # save logging
  save_freq: 2000
  log_freq: [2000, 2000, 500]         # [training loss, training images, val images]
  local_logging: True           # manually save images
  tf_logging: False             # tensorboard logging
  # validation settings
  use_ema_val: True
  val_freq: ${train.save_freq}
  val_y_channel: True
  val_resolution: ${model.params.lq_size}
  val_padding_mode: reflect
  # training setting
  use_amp: False             # amp training
  seed: 1234                 # random seed
  global_seeding: True
  # model compile
  compile:
    flag: False
    mode: reduce-overhead      # default, reduce-overhead
